# Generated by Django 3.0.2 on 2020-01-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=70)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.TextField()),
                ('fecha_adopcion', models.DateField()),
            ],
        ),
    ]
