# Generated by Django 3.0.2 on 2020-01-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0002_auto_20200129_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fecha_adopcion',
            field=models.DateField(blank=True),
        ),
    ]
